spring:
  application:
    name: issue-service

  datasource:
    url: jdbc:postgresql://localhost:5432/prlens
    username: prlens
    password: prlens
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092

server:
  port: 8081
