name: prlens

services:
  postgres:
    image: postgres:16
    container_name: prlens-postgres
    environment:
      POSTGRES_DB: prlens
      POSTGRES_USER: prlens
      POSTGRES_PASSWORD: prlens
    ports:
      - "5432:5432"
    volumes:
      - prlens_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: prlens-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: prlens-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: prlens-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: prlens-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://prlens-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: prlens-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: prlens-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: prlens-kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: prlens-zookeeper:2181
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: prlens-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prlens.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  prlens_postgres_data: