package com.prlens.docagent.agents;

import com.prlens.common.enums.ArtifactType;
import com.prlens.common.events.ArtifactGeneratedEvent;
import com.prlens.common.events.DocJobEvent;
import com.prlens.docagent.producer.ArtifactEventProducer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

@Slf4j
@Component
public class DesignDocAgent {
    private final ArtifactEventProducer artifactEventProducer;
    private final String outputDir;

    public DesignDocAgent(
            ArtifactEventProducer artifactEventProducer,
            @Value("${doc-agent.output-dir}") String outputDir
    ) {
        this.artifactEventProducer = artifactEventProducer;
        this.outputDir = outputDir;
    }

    public void generate(DocJobEvent event) {
        try {
            Files.createDirectories(Path.of(outputDir));

            String fileName = event.issueId() + ".md";
            Path filePath = Path.of(outputDir, fileName);

            String content = """
                    # Design Document

                    ## Issue

                    %s

                    ## Description

                    %s

                    ## Repository

                    %s

                    ## Proposed Solution

                    This is a mock design document generated by PRLens doc-agent.

                    ## Next Step

                    Trigger coding-agent to create a code change based on this design document.
                    """.formatted(
                    event.title(),
                    event.description(),
                    event.repository()
            );

            Files.writeString(filePath, content);
            log.info("Generated design document. issueId={}, path={}",
                    event.issueId(), filePath);

            ArtifactGeneratedEvent artifactEvent = new ArtifactGeneratedEvent(
                    UUID.randomUUID().toString(),
                    UUID.randomUUID().toString(),
                    event.issueId(),
                    ArtifactType.DESIGN_DOC,
                    filePath.toString(),
                    "doc-agent"
            );
            artifactEventProducer.publish(artifactEvent);
        } catch (IOException e) {
            log.error("Failed to design doc document. issueId = {}",
                    event.issueId(), e);
            throw new RuntimeException(e);
        }
    }

}
